### ISSUE TITLE
getChats() seems to return nothing

### ISSUE THREAD

**Issue by selvasoft** [andrew-ld/python-tdlib#1]
```
result = client.send(getChats(0,0,100))
print(result)
```

has the following output:
```
{"@type": "chats", "chat_ids": []}
```
I tried different variations and it returns nothing.
Am I doing this correctly?

**Comment by selvasoft** [comment]
thanks to @RusJr . this [line](https://github.com/RusJr/telega/blob/3892379a589915f62925a9734d31cd4551ed586a/telega/client.py#L203) reveals the answer to my qn. the first argument should be 
`2 ** 63 - 1` and not `0`. Now everything works fine now.

**Comment by RusJr** [comment]
> thanks to @RusJr . this [line](https://github.com/RusJr/telega/blob/3892379a589915f62925a9734d31cd4551ed586a/telega/client.py#L203) reveals the answer to my qn. the first argument should be
> `2 ** 63 - 1` and not `0`. Now everything works fine now.

not bad) How did you find me?

**Comment by selvasoft** [comment]
@RusJr Searched for tdlib library in pypi. Went to telega repo. Read your code and got the answer. Thats how I found you.
